// layout.js

import Head from "next/head";
import "./globals.css";

const RootLayout = ({ children }) => {
  return (
    <>
      <Head>
        {/* Include the link tags for Google Fonts */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
        />
      </Head>

      <html lang="en">
        <body>{children}</body>
      </html>
    </>
  );
};

export const metadata = {
  title: "HEIC",
  description: "Generated by create next app",
};

export default RootLayout;
